Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/ViewModels/DepositViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Volo.Lilit_Zarafyan.Repository.DepositCategory;

namespace Volo.Lilit_Zarafyan.MVC.ViewModel
{
    public class DepositViewModel
    {
        [HiddenInput]
        public int Id { get; set; }

        [Required(ErrorMessage = "It is required field")]
        public int BankId { get; set; }

        [Required(ErrorMessage = "It is required field")]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = "It is required field")]
        public int DepositId { get; set; }

        [Display(Name ="Start Date")]
        public System.DateTime StartDate { get; set; }

        [Required(ErrorMessage = "It is required field")]
        [Display(Name = "Estimated End Date")]
        [DataType(DataType.Date)]
        public System.DateTime EndDate { get; set; }

        [Required(ErrorMessage = "It is required field")]
        [Display(Name = "Start Sum(AMD)")]
        public decimal StartSum { get; set; }

        [Display(Name = "Total Profit Sum(AMD)")]
        public Nullable<decimal> TotalProfitSum { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ClosedDate { get; set; }

        public BankViewModel Bank { get; set; }

        public IEnumerable<BankViewModel> Banks { get; set; }

        public CustomerViewModel Customer { get; set; }

        public IEnumerable<CustomerViewModel> Customers { get; set; }

        [Display(Name ="Deposit Type")]
        public DepositTypeViewModel DepType { get; set; }

        public List<DepositTypeViewModel> DepTypes { get; set; }

    }
}

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Controllers/DepositsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Volo.Lilit_Zarafyan.Repository.DepositCategory;
using Volo.Lilit_Zarafyan.Repository.Entities;
using Volo.Lilit_Zarafyan.MVC.ViewModel;

namespace Volo.Lilit_Zarafyan.MVC.Areas.Admin.Controllers
{
    public class DepositsController : BaseController
    {

        // GET: Admin/Deposits
        public ActionResult Index()
        {
            IEnumerable<DepositViewModel> depositsVM = Mapper.ToViewModelCollection(_repository.SelectActiveDeposits(), _repository.SelectDepositTypes());
            return View(depositsVM);
        }

        // GET: Admin/Deposits
        public ActionResult ClosedDepositsList()
        {
            IEnumerable<DepositViewModel> depositsVM = Mapper.ToViewModelCollection(_repository.SelectClosedDeposits(), _repository.SelectDepositTypes());
            return View(depositsVM);
        }

        // GET: Admin/Deposits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DepositViewModel depositVM = Mapper.ToViewModel(_repository.Select<BankCustomerDeposit>(id.Value), _repository.SelectDepositTypes());
            if (depositVM == null)
            {
                return HttpNotFound();
            }
            return View(depositVM);
        }

        // GET: Admin/Deposits/Create
        public ActionResult Create(int? id)
        {
            DepositViewModel depositVM = new DepositViewModel();
            IEnumerable<BankViewModel> banksVM = Mapper.ToViewModelCollection(_repository.SelectActiveBanks());
            IEnumerable<CustomerViewModel> customersVM = Mapper.ToViewModelCollection(_repository.SelectValidCustomers());
            List<DepositTypeViewModel> dtypesVM = Mapper.ToViewModelCollection(_repository.SelectDepositTypes());
            depositVM.Banks = banksVM;
            depositVM.Customers = customersVM;
            depositVM.DepTypes = dtypesVM;
            ViewBag.DepositId = id;

            return View(depositVM);
        }

        // POST: Admin/Deposits/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "BankId, CustomerId,DepositId,StartDate,EndDate,StartSum")]DepositViewModel depositVM)
        {
            if (ModelState.IsValid)
            {
                BankCustomerDeposit deposit = Mapper.ToModel(depositVM);
                if (_repository.InsertDeposit(deposit))
                    return View("_CreateSuccess");
            }
            return View();
        }
        // GET: Admin/Deposits/Delete/5
        public ActionResult CloseDeposit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DepositViewModel depositVM = Mapper.ToViewModel(_repository.Select<BankCustomerDeposit>(id.Value), _repository.SelectDepositTypes());
             if (depositVM == null)
            {
                return HttpNotFound();
            }
            return View(depositVM);
        }

        // POST: Admin/Deposits/Delete/5
        [HttpPost]
        public ActionResult CloseDeposit(int id)
        {
            try
            {
                if (_repository.CloseDeposit(id))
                    return View("_ClosedSuccess");
                return View("Index");
            }
            catch
            {
                return View();
            }
        }


        public string CalculateProfit(int DepositId, decimal money, int periodInMonth)
        {
            return String.Format("{0:0.00}"+"AMD", _repository.CalculateProfit(DepositId, money, periodInMonth*30));
        }

    }
}

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Controllers/DepositsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Volo.Lilit_Zarafyan.Repository.DepositCategory;
using Volo.Lilit_Zarafyan.Repository.Entities;
using Volo.Lilit_Zarafyan.MVC.ViewModel;

namespace Volo.Lilit_Zarafyan.MVC.Controllers
{
    public class DepositsController : BaseController
    {

        // GET: Deposits/Create
        public ActionResult Create(int? id)
        {
            DepositViewModel depositVM = new DepositViewModel();
            IEnumerable<BankViewModel> banksVM = Mapper.ToViewModelCollection(_repository.SelectActiveBanks());
            IEnumerable<CustomerViewModel> customersVM = Mapper.ToViewModelCollection(_repository.SelectValidCustomers());
            List<DepositTypeViewModel> dtypesVM = Mapper.ToViewModelCollection(_repository.SelectDepositTypes());
            depositVM.Banks = banksVM;
            depositVM.Customers = customersVM;
            depositVM.DepTypes = dtypesVM;
            ViewBag.DepositId = id;

            return View(depositVM);
        }

        // POST: Deposits/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "BankId, CustomerId,DepositId,StartDate,EndDate,StartSum")]DepositViewModel depositVM)
        {
            if (ModelState.IsValid)
            {
                BankCustomerDeposit deposit = Mapper.ToModel(depositVM);
                if (_repository.InsertDeposit(deposit))
                    return View("_CreateSuccess");
            }
            return View();
        }

        public string CalculateProfit(int DepositId, decimal money, int periodInMonth)
        {
            return String.Format("{0:0.00}", _repository.CalculateProfit(DepositId, money, periodInMonth*30));
        }

    }
}

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Views/Deposits/CloseDeposit.cshtml
@model Volo.Lilit_Zarafyan.MVC.ViewModel.DepositViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Close Deposit</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Bank)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bank.BankInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Customer.FullName),
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepType.DepTypeInfo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartSum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartSum)
        </dd>
    </dl>

    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "close" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Close Deposit" class="btn btn-default" /><div id="close"></div> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Views/Deposits/ClosedDepositsList.cshtml
@model IEnumerable<Volo.Lilit_Zarafyan.MVC.ViewModel.DepositViewModel>

@{
    ViewBag.Title = "ClosedDeposits";
}

<h2>Closed Deposits List</h2>

<p>
    @Html.ActionLink("Back To Active Deposits List", "Index", "Deposits", new { area = "Admin" }, "")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Bank)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartSum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalProfitSum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClosedDate)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Bank.BankName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartSum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalProfitSum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClosedDate)
        </td>
       
    </tr>
}

</table>

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Views/Deposits/Create.cshtml
@model Volo.Lilit_Zarafyan.MVC.ViewModel.DepositViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create New Deposit</h2>
<!-- Trigger the modal with a button -->
<h3>
    Calculate your profit before creating Deposit
    <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Calculate</button>
</h3>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Calculate your profit before creating Deposit</h4>
            </div>
            <div class="modal-body">
                @using (Ajax.BeginForm("CalculateProfit", "Deposits", new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "calc" }))
                {
                    <div class="form-group">
                        @Html.DropDownListFor(model => model.DepositId, new SelectList(Model.DepTypes, "Id", "Name", @ViewBag.DepositId), "Select Deposit Type", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DepTypes, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <input type="number" name="money" placeholder="Enter Start Sum" class="form-control" required />
                        @Html.ValidationMessage("money", "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <input type="number" name="periodInMonth" placeholder="Enter Period in Month" class="form-control" required />
                        @Html.ValidationMessage("periodInMonth", "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <div>
                            <input type="submit" value="Calculate Profit" class="btn btn-info" />
                            <div id="calc"></div>
                        </div>
                    </div>
                }
            </div>
        </div>

    </div>
</div>
@using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "create" }))

{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BankId, "Bank", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BankId, new SelectList(Model.Banks, "Id", "BankName"), "Select....", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BankId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "Customer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CustomerId, new SelectList(Model.Customers, "Id", "FullName"), "Select....", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepTypes, "Deposit Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DepositId, new SelectList(Model.DepTypes, "Id", "Name"), "Select....", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepTypes, "", new { @class = "text-danger" })
            </div>
        </div>
         <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @Value = DateTime.Now.AddDays(1)} })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StartSum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartSum, new { htmlAttributes = new { @class = "form-control", @Value = "" } })
                @Html.ValidationMessageFor(model => model.StartSum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <div id="create"></div>
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Views/Deposits/Details.cshtml
@model Volo.Lilit_Zarafyan.MVC.ViewModel.DepositViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Deposit Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.Bank)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Bank.BankInfo),
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Customer.CustomerInfo)
        </dd>
       
        <dt>
            @Html.DisplayNameFor(model => model.DepType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DepType.DepTypeInfo),
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartSum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartSum)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Views/Deposits/Index.cshtml
@model IEnumerable<Volo.Lilit_Zarafyan.MVC.ViewModel.DepositViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Active Deposits List</h2>

<div class="mb-15">
    @Html.ActionLink("Create New", "Create", "Deposits", null, new { @class = "btn btn-primary" })
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Bank)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartSum)
        </th>
        <th>
            Actions
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Bank.BankName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepType.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartSum)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Close Deposit", "CloseDeposit", new { id=item.Id })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Show Closed Deposits List", "ClosedDepositsList", "Deposits", new { area = "Admin" }, "")
</p>

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Views/Deposits/_ClosedSuccess.cshtml
@model Volo.Lilit_Zarafyan.MVC.ViewModel.DepositViewModel

<h2>Deposit is closed on @DateTime.Now</h2>

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Areas/Admin/Views/Deposits/_CreateSuccess.cshtml
<h2>Success</h2>
<p>Deposit has been created successfully!</p>