Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Controllers/BanksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Volo.Lilit_Zarafyan.Repository.Entities;
using Volo.Lilit_Zarafyan.MVC.ViewModel;
using Volo.Lilit_Zarafyan.MVC.Areas.Admin.Controllers;

namespace Volo.Lilit_Zarafyan.MVC.Controllers
{
    public class BanksController : BaseController
    {
        // GET: Banks
        public ActionResult Index()
        {
            IEnumerable<BankViewModel> banksVM = Mapper.ToViewModelCollection(_repository.SelectActiveBanks());

            return View(banksVM);
        }

        // GET: Banks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BankViewModel bankVM = Mapper.ToViewModel(_repository.Select<Bank>(id.Value));
            if (bankVM == null)
            {
                return HttpNotFound();
            }
            return View(bankVM);
        }
    }
}

Volo.Lilit_Zarafyan/Volo.Lilit_Zarafyan.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Banking Deposit System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href='@Url.Action("Index", "Home", new { area = "" })' class="navbar-brand">
                    <img src='@Url.Content("~/Content/Images/logo.png")' />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Banks List", "Index", "Banks")</li>
                </ul>
                <div class="navbar-right">@Html.ActionLink("Admin Page", "Index", "Home", new { area = "Admin" }, "")</div>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>